### ISSUE TITLE
Include an instance of the verifier to be used in rails

### ISSUE THREAD

**Issue by fourcolors** [jnbt/candy_check#10]
It would be nice to do the configuration and initialization items for a rails app in the initializer then use the verifier in a controller. ie

`CandyCheck.verifier(params)`

**Comment by klaseskilson** [comment]
You can add a simple [initializer](http://guides.rubyonrails.org/configuring.html#using-initializer-files) to do this. I think that is a better solution in order to avoid to make this project Rails-specific.

**Comment by fourcolors** [comment]
@klaseskilson I kind of agree with that... hm.. I wrote a little wrapper for this gem to plug it into Rails. I'll publish once I get my feature developed out. 

Quick question, whats the whole "key_file" thing? https://developers.google.com/android-publisher/authorization doesn't reference that at all.

**Comment by fourcolors** [comment]
Ok, nm I found where to generate that file. These authentication systems are pretty complete sometimes.

**Comment by jnbt** [comment]
Thanks for opening #11.
