### ISSUE TITLE
add support for json key type vs p12

### ISSUE THREAD

**Issue by fourcolors** [jnbt/candy_check#11]
**system**
Google Play Store Authentication

**background**
The p12 system is a little out dated. Google recommends that we use the .json key file it would be nice to be able to use either a .json or p12 file

**expected behavior**
For the key file, you should be able to use a .json or p12 file

**Comment by jnbt** [comment]
You're totally right here. I think it makes sense to update the `google-api-client` dependency. I'll try to look into this soon, but sadly I'm currently under a high workload.

**Comment by jnbt** [comment]
In fact the p12-based key-storage seems to be deprecated. Maybe it is sufficient to go for a breaking change here and only support the JSON-based key file.

**Comment by fourcolors** [comment]
@jnbt I have a high workload for the next little bit too but could have some time in a week. 

It would be nice if there was a deprecation warning until a version bump for the JSON-based key file.

**Comment by jnbt** [comment]
@fourcolors FYI I started the implementation to support JSON key files for the PlayStore in d9dfad3888ba10ab0c26eff06129a6dd2cdc3dfe

I found a way to support the old p12 files (with a deprecation warning) and the new JSON key files.

**Comment by pablocrivella** [comment]
Hey @jnbt! Any updates on this issue? I willing to help with this project if you need me too!

**Comment by jnbt** [comment]
@pablocrivella I'm now back in the office after a long time handling other problems. I'm still willing to update the Google API client and include the other fixes. Currently my biggest headache is #8.

**Comment by jnbt** [comment]
Closing this issue, as support of JSON-based key files was introduced with version 0.2.0. See the [Migration Guide](https://github.com/jnbt/candy_check/blob/master/MIGRATION_GUIDE_0_2_0.md) for more information.
