### ISSUE TITLE
better README explanations for google play

### ISSUE THREAD

**Issue by fourcolors** [jnbt/candy_check#12]
**background**
there is some confusion about what some of the options are. For instance, where does one get the 'ApplicationName' or 'version number'

**plan**

explain where to find each of the values or at least what they are suppose to be.

**Comment by fourcolors** [comment]
I also noticed the `verify_subscription` doc's are incorrect. They use a `!` but in the code that's not implemented

**Comment by jnbt** [comment]
@fourcolors I've added some information about `application_name` and `application_version` to the README. Can you help me a little bit to locate the issue regarding the `verify_subscription!` mis-documentation?

**Comment by fourcolors** [comment]
Hey, crazy could of business days with my company so haven't been able to help out. Yeah I'll get to it. Just going to be a moment.

**Comment by jnbt** [comment]
The new PlayStore part of the gem is now much better explained in the README.
