### ISSUE TITLE
Incompatible with rails 5

### ISSUE THREAD

**Issue by sedubois** [jnbt/candy_check#18]
Hello and thank you for sharing your work. Do you plan to finish the upgrade of google API client that you started in [a branch](https://github.com/jnbt/candy_check/tree/update-google-api-client)? Right now candy_check is unusable because it requires google API client 0.8.7 which isn't compatible with Rails 5. 

If this library is no longer maintained, do you know another library to recommend for App Store and Google Play purchase receipt verification?

Thank you very much

**Comment by ricky-crichq** [comment]
Hey @sedubois, what is not compatible? Could you explain and/or provide a link?

Not a maintainer, just curious. We are using this gem fine on rails 5.0.2 but the google api client is pinned to 0.8.6.

**Comment by jnbt** [comment]
@sedubois: I'm now back in the office after a long time of handling other problems. I'll try catching up the issues in the next days. There is still the plan to update the Google API client, but I need some more time to test it. One of the most delaying fact it that I need to perform manual integration tests :-(

**Comment by sedubois** [comment]
Thanks @jnbt that would be great. Right now I’ll try pinning the version as suggested by @ricky-crichq, I’m just not very familiar with gems management (I took over maintenance of a Rails project).

**Comment by hugoh1995** [comment]
How do you guys pinn the google api client to a specific version ? @ricky-crichq Did you managed to make it work ? @sedubois

**Comment by sedubois** [comment]
Sorry @hugoh1995, I'm still stuck on Rails 4 and haven't yet decided if I'll upgrade or move to another framework entirely.

**Comment by pfeiffer** [comment]
Would be really great to bump dependency on google-api-client to maintain compatibility with newer versions of ruby (2.3.7, 2.4.x and 2.5):

See: https://github.com/google/google-api-ruby-client/pull/648
And: https://bugs.ruby-lang.org/issues/14664

**Comment by pfeiffer** [comment]
I see that it's (somehow) mitigated in https://github.com/jnbt/candy_check/pull/27 by setting the user agent manually. However in our case we're using google-api-client for other stuff as well, and it would be great to be able to use the client without having to manually set user agent and migrate to newer versions of the api-client :-)

**Comment by jnbt** [comment]
@pfeiffer I totally agree on this. Sadly I'm currently very limited in time and the newer Google API client has a totally different design and authentication mechanism.

**Comment by pfeiffer** [comment]
Totally understand! I appreciate the work you've done with this lib. I see that there's a branch with some changes.

Would it be possible for you do document what is missing, needs to be done etc. so I or someone else could take a stab at finishing it?

**Comment by jnbt** [comment]
Work has been started in #35
