### ISSUE TITLE
Gem uses server time zone to calculate the current day, not UTC

### ISSUE THREAD

**Issue by ricky-crichq** [jnbt/candy_check#20]
When running the tests on my local machine (New Zealand) there was one failure which was caused by time zone issues.

Using `Date.today` respects the machines local time zone when it should be using UTC.

The failed test:
```
1) Failure:
CandyCheck::PlayStore::Subscription::unexpired and renewing subscription#test_0002_is two days left until it is overdue [/Users/admin/Code/NuffieProductions/candy_check/spec/play_store/subscription_spec.rb:82]:
  Expected: -2
  Actual: -1
```

**Comment by jnbt** [comment]
Fix included in version `0.2.1`
