### ISSUE TITLE
No method to cancel subscription

### ISSUE THREAD

**Issue by zia-qamar** [jnbt/candy_check#25]
I want to cancel user subscription. But this gem does not provide any method for that, 
[Here](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/cancel) is documentation from google developer.

**Comment by klaseskilson** [comment]
Hi @zia-qamar, thanks for your comment. As of now, this Gem is pretty much read-only, to keep things aligned between the Apple and Google platform. I'm happy to take a look at a PR if you don't mind providing one though.
