### ISSUE TITLE
Permission denied for tmp/candy_check_play_store_cache

### ISSUE THREAD

**Issue by Faisal-nfl** [jnbt/candy_check#28]
I deployed project on cloud66 (digital ocean) & when I try to access rails console it gives permission error for tmp/candy_check_play_store_cache

`/var/deploy/kids/web_head/shared/bundle/ruby/2.3.0/gems/candy_check-0.1.1/lib/candy_check/play_store/discovery_repository.rb:27:in initialize: Permission denied @ rb_sysopen - tmp/candy_check_play_store_cache (Errno::EACCES)`

any solution for this?

**Comment by jnbt** [comment]
Currently a writeable volume is required. Once we migrated to the new Google API client (in #35) this should be obsolete.
