### ISSUE TITLE
google-api-client dependency outdated

### ISSUE THREAD

**Issue by ljachymczyk** [jnbt/candy_check#31]
candy_check requires google-api-client (~> 0.8.6) while the most up to date version available is 0.25.0 (https://rubygems.org/gems/google-api-client/versions/0.25.0).

Do you plan to update this dependency?

**Comment by jnbt** [comment]
Work for this is in progress in #35

**Comment by jnbt** [comment]
@pooja1690 I just gave the whole topic a higher priority on our companies schedule. We definitely need to adopt the new API also for our own projects. The plan is to assign one or two developers to this topic at the beginning of October.

**Comment by jnbt** [comment]
@christophweegen We need to push the efforts on this issue!

**Comment by pooja1690** [comment]
That helps. Thanks for the update @jnbt !

**Comment by nicolasevigo** [comment]
touching base, any update on this @jnbt?

**Comment by christophweegen** [comment]
Hello @nicolasevigo,

I'm working on this in https://github.com/jnbt/candy_check/pull/35 and it will be ready in the upcoming 2 weeks for sure, since we're relying on that feature too.

**Comment by jnbt** [comment]
Hi @nicolasevigo,

we updated the dependency. Sadly Google has changed the whole authentication system, so we needed to introduce some breaking changes to the PlayStore functionality. If you're upgrading from a CandyCheck version < 0.2.0 see the [Migration Guide](https://github.com/jnbt/candy_check/blob/master/MIGRATION_GUIDE_0_2_0.md) for more information.

Maybe you can try and give feedback!
