### ISSUE TITLE
Candy Check does not install latest changes of gems

### ISSUE THREAD

**Issue by sajjadmurtaza** [jnbt/candy_check#52]
When i try to add `candy_check`

It does not install [Add server ACK for consumable #50
](https://github.com/jnbt/candy_check/pull/50).

Even i tried to update the gem but still same results. i.e. `bundle update candy_check`

any suggestion/help will be appreciated

https://github.com/jnbt/candy_check/blob/master/lib/candy_check/play_store/acknowledger.rb
https://github.com/jnbt/candy_check/pull/50

**Comment by sajjadmurtaza** [comment]
I fixed this by using 

`gem 'candy_check', git: 'https://github.com/jnbt/candy_check', branch: 'master'
`

But i really want with gem version
`gem 'candy_check', '~> VERSION'
`

**Comment by christophweegen** [comment]
Hello @sajjadmurtaza thank you for your message.

The reason why you can't install it the usual way is because we haven't released a new gem version with the mentioned changes on rubygems.org yet.

I will do it tomorrow. I will keep you updated when it's done.

Greetings!

**Comment by christophweegen** [comment]
@sajjadmurtaza by the way if you're interested and don't know yet where Ruby finds it's gems (and how you can build a gem on your own) you can follow the official guides https://guides.rubygems.org/ 👍

**Comment by sajjadmurtaza** [comment]
@christophweegen thanks and please update when you will release it 🚀 .

Thanks in advance 👍 .

**Comment by christophweegen** [comment]
Hello @sajjadmurtaza, sorry for the late reply. I finally released a new version of candy_check. Version `0.3.0` is available via rubygems.org now. You're welcome.
