### ISSUE TITLE
Update google-api-client verison

### ISSUE THREAD

**Issue by Achilles718611** [jnbt/candy_check#55]
I noticed candy_check uses old google-api-client (0.34.1).
That gem has not new features which is supported by google's Purchaess.subscription.
For example, we have to have constant filed across all transactions for one user (in case of Apple original transaction id).
Google added filed called obfuscatedExternalProfileId for this purpose.
To use that filed, we have to use the latest goolgle-api-client.
When candy_check new version will be relased?

**Comment by christophweegen** [comment]
Hello @Achilles718611 sorry for the late reply. I just released candy_check `0.3.0`, which uses google-api-client `0.43.0`.

**Comment by Achilles718611** [comment]
Great, thank you.
