### ISSUE TITLE
unknown attribute 'in_app_ownership_type' for IosTransaction.

### ISSUE THREAD

**Issue by SergioSoftwhisper** [jnbt/candy_check#63]
Hi, we were trying to verify a receipt and we have got this error "unknown attribute 'in_app_ownership_type' for IosTransaction.".
We  have solved adding to the DB table "ios_transactions" the attribute "in_app_ownership_type" as string.
In November 2020 all works ok.

**Comment by jnbt** [comment]
@SergioSoftwhisper I'm a little bit lost on this topic, because this gems doesn't ship with any database connection at all. Can you provide some source code to showcase the problem?
