### ISSUE TITLE
Ruby 3.0.0 support

### ISSUE THREAD

**Issue by skliarov** [jnbt/candy_check#64]
@jnbt during upgrade from Ruby 2.7.1 to 3.0.0 `candy_check` downgrades, because of dependency on `google-api-client`. Another problem is that `google-api-client` is deprecated and needs to be replaced.

```
-    candy_check (0.1.2)
-      google-api-client (~> 0.8.6)
+    candy_check (0.0.1)
+      google-api-client (~> 0.8)
       multi_json (~> 1.10)
-      thor (~> 0.19)
```

Hardcoding the latest version of `candy_check` (0.4.0) in Gemfile does not work either.

```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby (~> 3.0.0.0)

    candy_check (= 0.4.0) was resolved to 0.4.0, which depends on
      google-api-client (~> 0.43.0) was resolved to 0.43.0, which depends on
        Ruby (~> 2.4)
```

**Comment by courtsimas** [comment]
Has there been any resolution to this?

**Comment by jnbt** [comment]
@skliarov Thanks for the report. I'm currently a little bit slow on contributions to this project, nevertheless we're still using it in production. Sadly my use-case involves an integration in JRuby which is currently not on the Ruby 3.0.0 train.

Luckily  @dsantosmerino started a PR with updated gem for the Google integration in #65. Maybe you want to try this PR if it solves your issues.

**Comment by christopheragnus** [comment]
Any progress on this?
