### ISSUE TITLE
Add ability to add Rails secret credentials hash

### ISSUE THREAD

**Issue by christopheragnus** [jnbt/candy_check#66]
Hey, 

I'm using this library for Rails. Is there a way we can replace the `File.open()` under `CandyCheck::PlayStore.authorization` with
`StringIO()`  or the ability to pass in an hash of encrypted Rails credentials (to avoid storing credentials publicly in Rails)?

```
credentials = { 
  type: "",
  private_key: Rails.application.credentials["SECRET_KEY"]
  ...
}

json_key_io: StringIO.new(credentials)
```

**Comment by fabn** [comment]
You can solve it by using this to build an authorization object:

```ruby
Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io: StringIO.new(Rails.application.credentials.android!.fetch(:service_account_credentials)),
      scope: "https://www.googleapis.com/auth/androidpublisher",
    )
```

**Comment by jnbt** [comment]
I agree on @fabn suggestion. The README also states to look for details in https://github.com/googleapis/google-auth-library-ruby

**Comment by rlabrovi** [comment]
I encoded google key json file content and stored it as environment variable. Main reason is security reason, didn't want to store ` key.json` file on server.

.env

`GOOGLE_APPLICATION_CREDENTIALS_JSON=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGlhbmEtY29uZm9ydGktYXBwIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNzdmNjBhYzNhYTIyZjM0YzhiMjkxMGNjMDJmNzdhOTg5NjJkMjI5YiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSd.........`

Then used it like @fabn suggested:

```ruby
key = Base64.decode64(ENV.fetch('GOOGLE_APPLICATION_CREDENTIALS_JSON'))

authorization = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: StringIO.new(key),
  scope: "https://www.googleapis.com/auth/androidpublisher",
)
```
