### ISSUE TITLE
invalid: Invalid Value

### ISSUE THREAD

**Issue by RenatoSerra22** [jnbt/candy_check#76]
Hello,

Im validating receipt on android and ios for subscriptions.
It seems to be doing things correctly for both.
Although on android one user in Turkey purchasing is causing `invalid: Invalid Value` http 400.
How do i find out what is wrong, i only have 1.5k MAU id be surprised if someone is trying to create a fake subscription.. but who knows

**Comment by jnbt** [comment]
I typically see the `400` errors in combination with rooted Android devices. There are some "tools" in the wild, which automatically hijack IAPs and subscribtions and create fake responses.

As long you don't have a larger amount of users affected by this, I would simply ignore it.
