### ISSUE TITLE
verify_subscription is not included on RubyGems gem

### ISSUE THREAD

**Issue by AhmedAttyah** [jnbt/candy_check#9]
The Gem file published on RubyGems doesn't have :verify_subscription method for some reason. Even though it is the same version as the latest on the repo. currently. I had to refer to this github repo. in my Gemfile in order to get it.

**Comment by klaseskilson** [comment]
AFAIK, @jnbt decided not to publish the subscription support yet since it is still lacking proper testing. See #7 and #8. Until this has been solved, you need to use the pre-release version here at GitHub.

**Comment by jnbt** [comment]
For convenience I've released a pre-release version to Rubygems: 

    gem "candy_check", "0.1.0.pre"

or

    $ gem install candy_check --pre

**Comment by jnbt** [comment]
@klaseskilson @AhmedAttyah Can you confirm that the subscription verification is working for sandbox and production?

**Comment by fourcolors** [comment]
I'm trying to get subscription working, right now running into an issue with an `undefined method 'to_hash' for nil:NilClass` when running verifiy_subscription on the verifier

**Comment by fourcolors** [comment]
Oh, that was an internal issue, not related never mind.

**Comment by jnbt** [comment]
Closes this issue, as the subscription support is now officially released in version `0.1.1` on rubygems.org
